import 'package:flutter/material.dart';import 'package:meal_connect/core/app_export.dart';import 'package:meal_connect/widgets/app_bar/appbar_leading_iconbutton_one.dart';import 'package:meal_connect/widgets/app_bar/appbar_title.dart';import 'package:meal_connect/widgets/app_bar/custom_app_bar.dart';import 'package:meal_connect/widgets/custom_elevated_button.dart';import 'package:meal_connect/widgets/custom_outlined_button.dart';class SelectLocationScreen extends StatelessWidget {const SelectLocationScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 31.h, vertical: 52.v), child: Column(children: [Text("Choose your location to see the NGO’s nearby", style: CustomTextStyles.titleMediumBluegray900Medium), SizedBox(height: 85.v), _buildSelectLocation(context), Spacer(), SizedBox(height: 6.v), CustomElevatedButton(text: "Continue", margin: EdgeInsets.symmetric(horizontal: 18.h), buttonStyle: CustomButtonStyles.fillBlueGray)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 55.h, leading: AppbarLeadingIconbuttonOne(imagePath: ImageConstant.imgUser, margin: EdgeInsets.only(left: 24.h, top: 12.v, bottom: 12.v), onTap: () {onTapUser(context);}), title: AppbarTitle(text: "Location", margin: EdgeInsets.only(left: 25.h))); } 
/// Section Widget
Widget _buildSelectLocation(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 4.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(children: [CustomOutlinedButton(height: 80.v, width: 163.h, text: "Basavangudi", buttonStyle: CustomButtonStyles.outlinePrimaryTL10, buttonTextStyle: CustomTextStyles.titleMediumPrimaryBold16, onPressed: () {onTapBasavangudi(context);}), SizedBox(height: 27.v), Container(width: 163.h, margin: EdgeInsets.only(right: 2.h), padding: EdgeInsets.symmetric(horizontal: 38.h, vertical: 29.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Text("JP nagar", style: CustomTextStyles.titleSmallPrimaryBold)), SizedBox(height: 32.v), Container(width: 163.h, margin: EdgeInsets.only(right: 2.h), padding: EdgeInsets.symmetric(horizontal: 36.h, vertical: 27.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Text("Girinagar", style: CustomTextStyles.titleMediumPrimaryBold16))]), Column(children: [Container(width: 163.h, padding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 27.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Text("Indiranagar", style: CustomTextStyles.titleMediumPrimaryBold16)), SizedBox(height: 25.v), Container(padding: EdgeInsets.symmetric(horizontal: 32.h, vertical: 26.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Text("Kormangala", style: CustomTextStyles.titleMediumPrimaryBold16)])), SizedBox(height: 34.v), Container(width: 163.h, padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 25.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Text("Malleshwaram", style: CustomTextStyles.titleMediumPrimaryBold16)]))])])); } 
/// Navigates to the signUpScreen when the action is triggered.
onTapUser(BuildContext context) { Navigator.pushNamed(context, AppRoutes.signUpScreen); } 
/// Navigates to the selectLocationSelectedScreen when the action is triggered.
onTapBasavangudi(BuildContext context) { Navigator.pushNamed(context, AppRoutes.selectLocationSelectedScreen); } 
 }
