name: meal_connect
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  smooth_page_indicator: ^1.1.0
  dotted_border: ^2.1.0
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  firebase_core: ^2.17.0
  firebase_analytics: ^10.8.0
  firebase_auth: ^4.16.0
  cloud_firestore: 4.14.0
  get: ^4.1.4
  firebase_database: ^10.1.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Plus Jakarta Sans
      fonts: 
        - asset: assets/fonts/PlusJakartaSansRomanBold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSansRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSansRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSansRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSansExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSansExtraLight.ttf
          weight: 200
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
