// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyCgjjQJDS4ny1HwfKV_rcLTLvjJ-Y-XBuE',
      appId: '1:200963182888:web:80e1e390ee28c1479c801d',
      messagingSenderId: '200963182888',
      projectId: 'meal-connect-7c7de',
      authDomain: 'meal-connect-7c7de.firebaseapp.com',
      storageBucket: 'meal-connect-7c7de.appspot.com',
      measurementId: 'G-9BQ0QSHP9N',
      databaseURL: 'https://meal-connect-7c7de-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyC2r5RebcJA2cu07AkTrR1-P7DUMc0I8G0',
      appId: '1:200963182888:android:48fca1a81bf788119c801d',
      messagingSenderId: '200963182888',
      projectId: 'meal-connect-7c7de',
      storageBucket: 'meal-connect-7c7de.appspot.com',
      databaseURL: 'https://meal-connect-7c7de-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAONrLrLC5gLCGWVt7RlC2YBHcMIYI5ggE',
    appId: '1:200963182888:ios:422de5577d5ebff59c801d',
    messagingSenderId: '200963182888',
    projectId: 'meal-connect-7c7de',
    storageBucket: 'meal-connect-7c7de.appspot.com',
    iosBundleId: 'com.mealconnect.app',
  );
}

