// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2r5RebcJA2cu07AkTrR1-P7DUMc0I8G0',
    appId: '1:200963182888:android:48fca1a81bf788119c801d',
    messagingSenderId: '200963182888',
    projectId: 'meal-connect-7c7de',
    databaseURL: 'https://meal-connect-7c7de-default-rtdb.firebaseio.com',
    storageBucket: 'meal-connect-7c7de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAONrLrLC5gLCGWVt7RlC2YBHcMIYI5ggE',
    appId: '1:200963182888:ios:422de5577d5ebff59c801d',
    messagingSenderId: '200963182888',
    projectId: 'meal-connect-7c7de',
    databaseURL: 'https://meal-connect-7c7de-default-rtdb.firebaseio.com',
    storageBucket: 'meal-connect-7c7de.appspot.com',
    androidClientId: '200963182888-uogc6e421f9cjofputa8unnhidv0q035.apps.googleusercontent.com',
    iosClientId: '200963182888-c9egbbir07cke50ug3su8879j7l9fl7t.apps.googleusercontent.com',
    iosBundleId: 'com.mealconnect.app',
  );
}
